export const REASON_CODES = {
    REVENUE_EMI_PASS: "REVENUE_SUPPORTS_ESTIMATED_REPAYMENT",
    REVENUE_EMI_FAIL: "INSUFFICIENT_REPAYMENT_CAPACITY",
    LOAN_REVENUE_PASS: "LOAN_AMOUNT_WITHIN_REVENUE_CAPACITY",
    LOAN_REVENUE_FAIL: "LOAN_AMOUNT_DISPROPORTIONATE_TO_REVENUE",
    TENURE_PASS: "TENURE_WITHIN_PREFERRED_RANGE",
    TENURE_FAIL: "TENURE_OUTSIDE_PREFERRED_RANGE",
    CONSISTENCY_PASS: "APPLICATION_DATA_CONSISTENT",
    CONSISTENCY_FAIL: "APPLICATION_DATA_INCONSISTENT"
};